export const RESTAURANT_GET_REQUEST = "RESTAURANT_GET_REQUEST";
export const RESTAURANT_GET_SUCCESS = "RESTAURANT_GET_SUCCESS";
export const RESTAURANT_GET_FAILURE = "RESTAURANT_GET_FAILURE";

export const RESTAURANT_FILTER_REQUEST = "RESTAURANT_FILTER_REQUEST";
export const RESTAURANT_FILTER_SUCCESS = "RESTAURANT_FILTER_SUCCESS";
export const RESTAURANT_FILTER_FAILURE = "RESTAURANT_FILTER_FAILURE";
